$(function(){
    $(".introduction").hide();

    $("#os1").click(function(){
		$("#i1").slideToggle();
	});
	$("#os2").click(function(){
		$("#i2").slideToggle();
	});
	$("#os3").click(function(){
		$("#i3").slideToggle();
	});
	//$("#os4").click(function(){
	//	$("#i4").slideToggle();
	//});
	$("#os4").click(function(){
		$("#i4").slideToggle();
	});
	$("#os5").click(function(){
		$("#i5").slideToggle();
	});
	$("#os6").click(function(){
		$("#i6").slideToggle();
	});
	$("#os7").click(function(){
		$("#i7").slideToggle();
	});
	$("#os8").click(function(){
		$("#i8").slideToggle();
	});
	$("#os9").click(function(){
		$("#i9").slideToggle();
	});
	$("#os10").click(function(){
		$("#i10").slideToggle();
	});
	$("#os11").click(function(){
		$("#i11").slideToggle();
	});
	$("#os12").click(function(){
		$("#i12").slideToggle();
	});
	$("#os13").click(function(){
		$("#i13").slideToggle();
	});
	$("#os14").click(function(){
		$("#i14").slideToggle();
	});
	$("#os15").click(function(){
		$("#i15").slideToggle();
	});
	$("#os16").click(function(){
		$("#i16").slideToggle();
	});
	$("#os17").click(function(){
		$("#i17").slideToggle();
	});
	$("#os18").click(function(){
		$("#i18").slideToggle();
	});
	$("#os19").click(function(){
		$("#i19").slideToggle();
	});
	$("#os20").click(function(){
		$("#i20").slideToggle();
	});
	$("#os21").click(function(){
		$("#i21").slideToggle();
	});
	$("#os22").click(function(){
		$("#i22").slideToggle();
	});
	$("#os23").click(function(){
		$("#i23").slideToggle();
	});
	$("#os24").click(function(){
		$("#i24").slideToggle();
	});
	$("#os25").click(function(){
		$("#i25").slideToggle();
	});
	$("#os26").click(function(){
		$("#i26").slideToggle();
	});
	$("#os27").click(function(){
		$("#i27").slideToggle();
	});
	$("#os28").click(function(){
		$("#i28").slideToggle();
	});
	$("#os29").click(function(){
		$("#i29").slideToggle();
	});
	$("#os30").click(function(){
		$("#i30").slideToggle();
	});
	$("#os31").click(function(){
		$("#i31").slideToggle();
	});
	$("#os32").click(function(){
		$("#i32").slideToggle();
	});
});